#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mknod -m 666 /dev/tty1    c 4 1 2>/dev/null || true
mknod -m 666 /dev/console c 5 1 2>/dev/null || true
mknod -m 666 /dev/null    c 1 3 2>/dev/null || true
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts 2>/dev/null || true
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run
echo "jaglinux" > /proc/sys/kernel/hostname
ip link set lo up 2>/dev/null || true
clear
cat /etc/issue
